name: MailPlugin
version: 1.0
api: 3.0.1
author: HmmHmmmmm
main: hmmhmmmm\mail\Mail
description:
- Facebook https://m.facebook.com/phonlakrit.knaongam.1
- Youtube https://m.youtube.com/channel/UCtjvLXDxDAUt-8CXV1eWevA
- Github https://github.com/HmmHmmmm

permissions:
    mail.command:
        default: false
        children:
            mail.command.mail:
                default: true