name: MailPlugin
version: 3.5
api: 3.11.0
author: HmmHmmmmm
main: hmmhmmmm\mail\Mail
website: https://github.com/HmmHmmmm/MailPlugin

permissions:
  mail:
    default: false
    children:
      mail.command:
        default: false
        children:
          mail.command.info:
            default: op
          mail.command.write:
            default: true
          mail.command.read:
            default: true
          mail.command.readall:
            default: true
          mail.command.clear:
            default: true
          mail.command.clearall:
            default: true
          mail.command.see:
            default: true
  report:
    default: false
    children:
      report.command:
        default: true