name: AeroMail
version: 4
api: 4.0.0
author: FiePaw
main: hmmhmmmm\mail\Mail

permissions:
  mail.command:
    default: true
  mail.command.info:
     default: op
  mail.command.write:
      default: true
  mail.command.read:
    default: true
  mail.command.readall:
    default: true
  mail.command.clear:
    default: true
  mail.command.clearall:
    default: true
  mail.command.see:
    default: true